server:
  port: 8080

spring:
  application:
    name: journal-trend-tracker
  datasource:
    url: jdbc:mysql://localhost:3306/journal_tracker_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.web: INFO
    com.journaltracker: DEBUG
